name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run install and tests
        run: |
          yarn
          yarn lint
          yarn test
          yarn test-e2e --repeat-flaky 3
          yarn test-e2e:10 --repeat-flaky 3
        env:
          CI: true
